CREATE TABLE IF NOT EXISTS results (
	code CHAR(6) NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	email CITEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	created TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
