DO $$ BEGIN CREATE DOMAIN INDEX INT CHECK (VALUE >= 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN GAME_CODE CHAR(6);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN PLAYER_ID CHAR(10);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN PLAYER_NAME VARCHAR(20) CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN PLAYER_POINTS INT CHECK (VALUE >= 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN QUESTION VARCHAR(200) CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

DO $$ BEGIN CREATE DOMAIN ANSWER VARCHAR(200) CHECK (LENGTH(VALUE) > 0);
EXCEPTION WHEN DUPLICATE_OBJECT THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS games (
	code GAME_CODE NOT NULL PRIMARY KEY,
	next GAME_CODE,
	completed TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS players (
	game_code GAME_CODE NOT NULL REFERENCES games(code) ON DELETE CASCADE,
	id PLAYER_ID NOT NULL PRIMARY KEY,
	name PLAYER_NAME NOT NULL,
	points PLAYER_POINTS NOT NULL
);

CREATE TABLE IF NOT EXISTS questions (
	game_code GAME_CODE NOT NULL REFERENCES games(code) ON DELETE CASCADE,
	index INDEX NOT NULL,
	name PLAYER_NAME NOT NULL,
	question QUESTION NOT NULL,
	PRIMARY KEY (game_code, index)
);

CREATE TABLE IF NOT EXISTS answers (
	game_code GAME_CODE NOT NULL,
	question_index INDEX NOT NULL,
	index INDEX NOT NULL,
	name PLAYER_NAME NOT NULL,
	answer ANSWER NOT NULL,
	FOREIGN KEY (game_code, question_index) REFERENCES questions(game_code, index) ON DELETE CASCADE,
	PRIMARY KEY (game_code, question_index, index)
);
